name: Публикация NuGet (при изменении версии)

on:
  push:
    paths:
      - 'Directory.Build.props'

jobs:
  publish:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        fetch-depth: 2

    - name: Настройка .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '8.x'
  
    - name: Установка xmllint
      run: sudo apt-get update && sudo apt-get install -y libxml2-utils

    - name: Проверка изменения версии
      id: check_version
      run: |
        git show HEAD^:Directory.Build.props > old.props || echo "<Version>none</Version>" > old.props
        NEW=$(xmllint --xpath "string(//Version)" Directory.Build.props)
        OLD=$(xmllint --xpath "string(//Version)" old.props || echo "none")
        echo "OLD=$OLD"
        echo "NEW=$NEW"
        if [ "$NEW" != "$OLD" ]; then
          echo "version_changed=true" >> $GITHUB_OUTPUT
        else
          echo "version_changed=false" >> $GITHUB_OUTPUT
        fi

    - name: Восстановление зависимостей
      run: dotnet restore

    - name: Сборка
      run: dotnet build -c Release --no-restore

    - name: Формирование пакетов
      if: steps.check_version.outputs.version_changed == 'true'
      run: dotnet pack -c Release --no-build -o ./nupkgs

    - name: Публикация NuGet пакетов
      if: steps.check_version.outputs.version_changed == 'true'
      run: dotnet nuget push "./nupkgs/*.nupkg" --api-key ${{ secrets.NUGET_API_KEY }} --source https://api.nuget.org/v3/index.json